# Generated by Django 3.2.9 on 2021-12-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='任务名称')),
                ('description', models.TextField(blank=True, max_length=200, verbose_name='任务描述')),
                ('start_date', models.DateTimeField(null=True, verbose_name='开始时间')),
                ('task_type', models.SmallIntegerField(choices=[(0, '单次任务'), (1, '定时任务')], default=0, verbose_name='任务类型')),
            ],
        ),
    ]
