# Generated by Django 3.2.9 on 2021-12-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='duration',
            field=models.IntegerField(default=60, verbose_name='执行时长（秒）'),
        ),
        migrations.AddField(
            model_name='task',
            name='interval',
            field=models.IntegerField(default=5, verbose_name='执行间隔（秒）'),
        ),
    ]
