# Generated by Django 3.2.9 on 2021-12-10 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_mgmt', '0002_auto_20211209_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '待执行'), (1, '正在执行'), (2, '已执行')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.SmallIntegerField(choices=[(0, '定时任务'), (1, '单次任务')], default=0, verbose_name='任务类型'),
        ),
    ]
