# Generated by Django 3.2.9 on 2021-12-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_mgmt', '0003_auto_20211210_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField()),
                ('time', models.DateTimeField(null=True)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
