# Generated by Django 3.2.9 on 2021-12-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_mgmt', '0004_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '待执行'), (1, '正在执行'), (2, '已执行'), (3, '已停止')], default=0, verbose_name='状态'),
        ),
    ]
