# Generated by Django 3.2.9 on 2021-12-21 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_mgmt', '0006_auto_20211215_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='day_of_month',
            field=models.CharField(blank=True, max_length=500, verbose_name='每月几号执行？'),
        ),
        migrations.AddField(
            model_name='task',
            name='execute_time',
            field=models.TimeField(null=True, verbose_name='何时执行？'),
        ),
        migrations.AddField(
            model_name='task',
            name='month_of_year',
            field=models.CharField(blank=True, max_length=500, verbose_name='几月执行？'),
        ),
        migrations.AddField(
            model_name='task',
            name='week',
            field=models.CharField(blank=True, max_length=500, verbose_name='周几执行？'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '待执行'), (1, '正在执行'), (2, '已结束')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.SmallIntegerField(choices=[(0, '每天'), (1, '每周'), (2, '每月'), (3, '一次')], default=0, verbose_name='希望任务多久执行一次？'),
        ),
    ]
